fixtures:
  repositories:
    augeas_core: 'https://github.com/puppetlabs/puppetlabs-augeas_core'
    concat:      'https://github.com/puppetlabs/puppetlabs-concat'
    stdlib:      'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    systemd:     'https://github.com/voxpupuli/puppet-systemd'
