fixtures:
  repositories:
    augeas_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-augeas_core'
      puppet_version: '>= 6.0.0'
    concat:      'https://github.com/puppetlabs/puppetlabs-concat'
    stdlib:      'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    systemd:     'https://github.com/camptocamp/puppet-systemd'
