name    'theforeman-dhcp'
version '1.2.0'
source 'git://github.com/theforeman/puppet-dhcp'
author 'ZLeslie, theforeman'
license 'Apache License Version 2.0'
summary 'Manage the ISC DHCP Daemon'
description 'A Puppet module to deploy and manage the ISC DHCP server.'
project_page 'http://github.com/theforeman/foreman-installer'

dependency 'theforeman/concat_native', '>= 1.2.0'
